name: Github Actios
on: push

jobs:
  Gitbuild:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up python
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: install dependancies
      run: |
        python -m pip install --upgrade pip
        pip install pytest 

    - name: Run py script
      run: |
        cd src
        python -m pytest addition.py
